[TSK-137] List Research Context Page
dream-aim-deliver/websat-planckster pull request #43
Opened 2024-09-16 19:54 UTC by ydamit

All the connections and pieces necessary for listing Research Contexts on the main site page.

2024-09-26 16:04 UTC, ydamit commented
I think the only remaining error results from the changes to the `status` property on the view model, which aren't reflected in the UI kit. Not sure what our process is for addressing cross-repo issues like that...

2024-10-28 18:34 UTC, maany commented
@MytsV is taking over ;) She will resolve the ui-kit if needed

2024-11-01 15:30 UTC, MytsV requested changes
I faced issues with the IOC running the app. Apart from using signals container in tRPC, server container requires another binding.
```ts
serverContainer
    .bind<interfaces.Factory<ListResearchContextsInputPort>>(USECASE_FACTORY.LIST_RESEARCH_CONTEXTS)
    .toFactory<ListResearchContextsInputPort, [Signal<TListResearchContextsViewModel>]>((context: interfaces.Context) => (response: Signal<TListResearchContextsViewModel>) => {
        const sourceDataGateway = context.container.get<KernelResearchContextGateway>(GATEWAYS.KERNEL_RESEARCH_CONTEXT_GATEWAY);
        const presenter = new BrowserListResearchContextsPresenter(response);
        const usecase = new ListResearchContextsUsecase(presenter, sourceDataGateway);
        return usecase;
    });
```
These both changes resolved the issue and the contexts get displayed fine otherwise.

2024-11-01 15:30 UTC, MytsV commented on src/lib/infrastructure/server/trpc/routers/research-contexts/list-research-contexts-router.ts
> +        const signalFactory = serverContainer.get<(initialValue: TListResearchContextsViewModel, update?: (value: TListResearchContextsViewModel) => void) => Signal<TListResearchContextsViewModel>>(S
Here a signalsContainer should be used instead, as otherwise the symbol cannot be found

2024-11-03 16:06 UTC, maany commented
Closed in favor of #50

2024-11-03 16:06 UTC, closed without merging